select O.ORDER_ID, M.CUSTOMER_NAME, O.ORDER_DATE, 
G.GOODS_NAME, O.BUY_QUANTITY, O.GOODS_BUY_PRICE, 
(O.BUY_QUANTITY*O.GOODS_BUY_PRICE) COST 
from BEVERAGE_ORDER o
inner JOIN BEVERAGE_MEMBER m
on O.CUSTOMER_ID = M.IDENTIFICATION_NO 
inner JOIN BEVERAGE_GOODS g
on O.GOODS_ID = G.GOODS_ID
--WHERE O.GOODS_BUY_PRICE BETWEEN 10 AND 20;
--where O.ORDER_DATE between '2020-12-01 00:00:00' and '2021-01-10 00:00:00';
WHERE O.ORDER_DATE between TO_TIMESTAMP('2020-12-01', 'YYYY-MM-DD') AND TO_TIMESTAMP('2021-12-01', 'YYYY-MM-DD');


select * from
(SELECT ROWNUM ROW_NUM, GOODS_ID, GOODS_NAME, 
PRICE, QUANTITY,IMAGE_NAME, STATUS 
FROM BEVERAGE_GOODS
where STATUS = 1
and QUANTITY >0)
where ROW_NUM between 1 and 6;

select COUNT(*)count from BEVERAGE_GOODS
where STATUS = 1 and QUANTITY >0;

select * from (
select ROWNUM ROW_NUM, GOODS_ID, GOODS_NAME,
PRICE, QUANTITY,IMAGE_NAME, STATUS
from BEVERAGE_GOODS WHERE STATUS = 1
and QUANTITY >0 
and UPPER(GOODS_NAME) like '%CO%')
where ROW_NUM between 1 and 6 ;

DELETE BEVERAGE_GOODS where GOODS_ID = ?;
--如果該元素已經被購買過
--integrity constraint (LOCAL.BEVERAGE_GOODS_FK) violated - child record found
